name: hsm
description: "Higher Self Method Oracle Cards"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  rxdart: ^0.27.7
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^13.0.0
  flutter_animate: ^4.3.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  loop_page_view: ^1.2.5
  google_fonts: 6.1.0
  appwrite: ^11.0.1
  fpdart: ^1.1.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  audioplayers: ^5.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  riverpod_generator:
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.1
  riverpod_lint:
  custom_lint:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
  - assets/cards/
  - assets/elements/