// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNsuIRo1vFagtmHD8syKpVcpnTyWnBf1Y',
    appId: '1:195982830409:web:d6527e0515b7c18cc20898',
    messagingSenderId: '195982830409',
    projectId: 'hsm-app-1b7e3',
    authDomain: 'hsm-app-1b7e3.firebaseapp.com',
    databaseURL: 'https://hsm-app-1b7e3-default-rtdb.firebaseio.com',
    storageBucket: 'hsm-app-1b7e3.appspot.com',
    measurementId: 'G-4197T23ZNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlMuFjULQ3QcFeRejstAlpMP3od-MMYQw',
    appId: '1:195982830409:android:f5eb4dd48a9bfc6ec20898',
    messagingSenderId: '195982830409',
    projectId: 'hsm-app-1b7e3',
    databaseURL: 'https://hsm-app-1b7e3-default-rtdb.firebaseio.com',
    storageBucket: 'hsm-app-1b7e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOlTbkWqY6KcN3Rf1TSEF8iDALOoM46jk',
    appId: '1:195982830409:ios:a272d3a2e77325a4c20898',
    messagingSenderId: '195982830409',
    projectId: 'hsm-app-1b7e3',
    databaseURL: 'https://hsm-app-1b7e3-default-rtdb.firebaseio.com',
    storageBucket: 'hsm-app-1b7e3.appspot.com',
    iosClientId: '195982830409-8qjn0joebdr69u0qvtbc02t3731ikg07.apps.googleusercontent.com',
    iosBundleId: 'media.andcut.hsm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOlTbkWqY6KcN3Rf1TSEF8iDALOoM46jk',
    appId: '1:195982830409:ios:ab0fe65068e78f53c20898',
    messagingSenderId: '195982830409',
    projectId: 'hsm-app-1b7e3',
    databaseURL: 'https://hsm-app-1b7e3-default-rtdb.firebaseio.com',
    storageBucket: 'hsm-app-1b7e3.appspot.com',
    iosClientId: '195982830409-c00o43tt0g6iobitsisjir8sq1nd22du.apps.googleusercontent.com',
    iosBundleId: 'media.andcut.hsm.RunnerTests',
  );
}
